# ----------------------------------------
# Created on: Tue Oct 25 10:10:55 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "F:/modeltech64_10.4/pango_sim_libraries/usim"
vmap  adc "F:/modeltech64_10.4/pango_sim_libraries/adc"
vmap  ddrc "F:/modeltech64_10.4/pango_sim_libraries/ddrc"
vmap  ddrphy "F:/modeltech64_10.4/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "F:/modeltech64_10.4/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "F:/modeltech64_10.4/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "F:/modeltech64_10.4/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "F:/modeltech64_10.4/pango_sim_libraries/pciegen2"
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_pll/rtl/ip_pll.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_pll/prj/ipcore/pll_clk/pll_clk.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_pll/sim/tb/tb_ip_pll.v" -work work

# ----------------------------------------
