# ----------------------------------------
# Created on: Tue Oct 18 13:50:15 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "F:/modeltech64_10.4/pango_sim_libraries/usim"
vmap  adc "F:/modeltech64_10.4/pango_sim_libraries/adc"
vmap  ddrc "F:/modeltech64_10.4/pango_sim_libraries/ddrc"
vmap  ddrphy "F:/modeltech64_10.4/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "F:/modeltech64_10.4/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "F:/modeltech64_10.4/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "F:/modeltech64_10.4/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "F:/modeltech64_10.4/pango_sim_libraries/pciegen2"
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/rtl/ram_wr.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/rtl/ram_rd.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/rtl/ip_2port_ram.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/prj/ipcore/ram_2port/rtl/ipml_sdpram_v1_6_ram_2port.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/prj/ipcore/ram_2port/ram_2port.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/prj/ipcore/pll_clk/pll_clk.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/ip_2port_ram/sim/tb/ip_2port_ram_tb.v" -work work

# ----------------------------------------
