# ----------------------------------------
# Created on: Tue Oct 25 10:01:56 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "F:/modeltech64_10.4/pango_sim_libraries/usim"
vmap  adc "F:/modeltech64_10.4/pango_sim_libraries/adc"
vmap  ddrc "F:/modeltech64_10.4/pango_sim_libraries/ddrc"
vmap  ddrphy "F:/modeltech64_10.4/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "F:/modeltech64_10.4/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "F:/modeltech64_10.4/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "F:/modeltech64_10.4/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "F:/modeltech64_10.4/pango_sim_libraries/pciegen2"
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/rtl/ip_fifo.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/rtl/fifo_rd.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/rtl/fifo_wr.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/prj/ipcore/fifo_generator_0/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/prj/ipcore/fifo_generator_0/rtl/ipml_sdpram_v1_6_fifo_generator_0.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/prj/ipcore/fifo_generator_0/rtl/ipml_fifo_v1_6_fifo_generator_0.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/prj/ipcore/fifo_generator_0/fifo_generator_0.v" -work work
vlog   "C:/Users/ch/Desktop/2021.4-SP1.2/ip_fifo/sim/tb/tb_ip_fifo.v" -work work

# ----------------------------------------
